/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libjdate;

import java.awt.Color;
import java.beans.Visibility;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author 0098iran
 */
public class CalenderPanel extends javax.swing.JPanel {

   tabdilatshamsi tb;
   int y,m,d,lengthDay;
    public CalenderPanel() {
        initComponents();
        setBackground(Color.WHITE);
        loading();
    }
void loading(){
    
        tb = new tabdilatshamsi();
        int[]a=tb.emrozShamsi();
           y=a[0];
           m=a[1];
           d=a[2];
           lengthDay=tb.lengthofdaymon(y, m);
           years.setText(y+"");
           moth.setText(m+"");
           day.setText(d+"");
           res.setText(tb.ForStringDay(y, m, d)+"   "+d+"  "+tb.FA_moon[m-1]+"  "+y);
            
           
           
           
           
    }


 private void setday() {
if(d<1){
        
        d=lengthDay;
        }else if(d>lengthDay){
        
        d=1;
        }
        day.setText(d+"");
        res.setText(tb.ForStringDay(y, m, d)+"   "+d+"  "+tb.FA_moon[m-1]+"  "+y);
     
    }
    private void setmonth(){
    
        if(m<1){
        m=12;
        }else if(m>12){
        m=1;
        }
        moth.setText(m+"");
        
lengthDay=tb.lengthofdaymon(y, m);
        setday();
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        py = new javax.swing.JButton();
        zy = new javax.swing.JButton();
        pm = new javax.swing.JButton();
        zm = new javax.swing.JButton();
        pd = new javax.swing.JButton();
        zd = new javax.swing.JButton();
        res = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        years = new javax.swing.JLabel();
        moth = new javax.swing.JLabel();
        day = new javax.swing.JLabel();

        py.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        py.setText("+");
        py.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyActionPerformed(evt);
            }
        });

        zy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        zy.setText("-");
        zy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zyActionPerformed(evt);
            }
        });

        pm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pm.setText("+");
        pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmActionPerformed(evt);
            }
        });

        zm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        zm.setText("-");
        zm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmActionPerformed(evt);
            }
        });

        pd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pd.setText("+");
        pd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdActionPerformed(evt);
            }
        });

        zd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        zd.setText("-");
        zd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zdActionPerformed(evt);
            }
        });

        res.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        res.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        years.setBackground(new java.awt.Color(204, 204, 0));
        years.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        years.setText("jLabel1");
        years.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(years);

        moth.setBackground(new java.awt.Color(255, 255, 255));
        moth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moth.setText("jLabel2");
        moth.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(moth);

        day.setBackground(new java.awt.Color(255, 255, 255));
        day.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        day.setText("jLabel3");
        day.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(day);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(res, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(zy, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(zm, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(zd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(py, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 8, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(py)
                    .addComponent(pm)
                    .addComponent(pd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zy)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(zd)
                        .addComponent(zm)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(res)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyActionPerformed
        // TODO add your handling code here:
        y++;
        if(y>1507){
            y=1210;

        }
        years.setText(y+"");
        setmonth();
    }//GEN-LAST:event_pyActionPerformed

    private void zyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zyActionPerformed
        // TODO add your handling code here:
        y--;
        if(y<1210){
            y=1507;
        }
        years.setText(y+"");
        setmonth();
    }//GEN-LAST:event_zyActionPerformed

    private void pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmActionPerformed
        // TODO add your handling code here:
        m++;
        setmonth();
    }//GEN-LAST:event_pmActionPerformed

    private void zmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmActionPerformed
        // TODO add your handling code here:
        m--;
        setmonth();
    }//GEN-LAST:event_zmActionPerformed

    private void pdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdActionPerformed
        // TODO add your handling code here:
        d++;
        setday();

    }//GEN-LAST:event_pdActionPerformed

    private void zdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zdActionPerformed
        // TODO add your handling code here:
        d--;

        setday();

    }//GEN-LAST:event_zdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel day;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel moth;
    private javax.swing.JButton pd;
    private javax.swing.JButton pm;
    private javax.swing.JButton py;
    private javax.swing.JLabel res;
    private javax.swing.JLabel years;
    private javax.swing.JButton zd;
    private javax.swing.JButton zm;
    private javax.swing.JButton zy;
    // End of variables declaration//GEN-END:variables

    private void Visibility(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
